### ISSUE TITLE
Add legend or <abbr> tag for dob job type and status

### ISSUE THREAD

**Issue by grischard** [jmapb/nycaabs#5]
This is currently undocumented.

Job type is NB (New building?), A1/A2/A3 (Alteration type 1, 2 or 3), etc.

Status are R, X, J, others?

**Comment by jmapb** [comment]
Good idea... I recently added the job type code list, as described in BIS, to the app.js comments, but I can imagine that someone may someday want to use this tool without reading through all the code first ;)

* A1 = ALTERATION TYPE 1
* A2 = ALTERATION TYPE 2
* A3 = ALTERATION TYPE 3
* DM = FULL DEMOLITION
* NB = NEW BUILDING
* PA = PLACE OF ASSEMBLY
* PR = LAA (ARA)
* SC = SUBDIVISION - CONDO
* SG = SIGN
* SI = SUBDIVISION - IMPROVED
* SU = SUBDIVISION - UNIMPROVED

"PLACE OF ASSEMBLY" is a little mysterious. I've seen churches described as "place of assembly" in BIS. Does DOB have a job type for the consecration of places of worship? 

"LAA (ARA)" is also mysterious, especially as an expansion of "PR". My best guess is that it means "Limited Alteration Application (Alteration Repair Application)". See https://www1.nyc.gov/site/buildings/industry/limited-alteration-application.page https://www.nyc.gov/html/dob/downloads/ppn/oppn0300.shtml

As far as the status codes, I found this at https://www1.nyc.gov/site/buildings/industry/permit-type-and-job-status-codes.page

* A = Pre-Filed,Pre-Filing
* B = A/P Unpaid,Application Processed - Part-No Payment
* C = A/P to D.E.A.R,Application Processed - Payment Only
* D = A/P Entire,Application Processed - Completed
* E = AP-NPE,Application Processed - No Plan Exam
* F = Assigned To P/E,Application Assigned To Plan Examiner
* G = PAA Fee Due,PAA Fee Due
* H = P/E In Process,Plan Exam - In Process
* I = Sign-Off,Sign-Off (ARA)
* J = P/E Disapproved,Plan Exam - Disapproved
* K = P/E Partial APRV,Plan Exam - Partial Approval
* L = P/E PAA $ Pending,P/E PAA - Pending Fee Estimation
* M = P/E PAA $ Resolvd,P/E PAA - Fee Resolved
* P = Approved,Plan Exam - Approved
* Q = Permit-Partial,Permit Issued - Partial Job
* R = Permit-Entire,Permit Issued - Entire Job/Work
* U = Completed,Completed
* X = Signed-Off,Signed-Off
* 3 = Suspended,Suspended

**Comment by jmapb** [comment]
Resolved with https://github.com/jmapb/nycaabs/commit/dd306af1ac636018fed05ca733be397771152ae8
