### ISSUE TITLE
Include shortcut link to Cyclomedia Street View

### ISSUE THREAD

**Issue by mxxcon** [jmapb/nycaabs#8]
On ZoLa's property view at the very bottom of the page there's a link to open Cyclomedia's Street View. It would be great if this app extracted that shortcut. Makes it quicker to confirm various data.

**Comment by jmapb** [comment]
Agreed, Cyclomedia can be useful for disambiguation. I added a Cyclomedia link from the right-click map context menu a couple of months ago. It's the version hosted at geocoder.nyc which has some improvements over the one ZoLa links to (at planninglabs.nyc.)

**Comment by mxxcon** [comment]
This is awesome. I didn't know I could right-click on that map 👍🙂
